apiVersion: v1
kind: Pod
metadata:
  name: esscd-deployment
spec:
  containers:
  - image: rainboltz/esscd-k8s
    imagePullPolicy: IfNotPresent
    name: esscd-deployment
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: Default

